sudo: required

language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev" # 3.5 development branch
  - "nightly" # currently points to 3.6-dev

services:
  - docker

before_install:
  - docker build -t oyvindio/ifconfig.py .
  - docker run --detach --publish 127.0.0.1:8888:8888 --name ifconfig.py oyvindio/ifconfig.py
  - docker ps --all

script:
  - python smoketest.py http://127.0.0.1:8888
